### ISSUE TITLE
Dark Mode Problem

### ISSUE THREAD

**Issue by excalibur1010** [g-fb/mangareader#1]
![image](https://user-images.githubusercontent.com/58497792/179428484-eb392ae6-9eea-4607-ba7e-c1aed20048f3.png)
![image](https://user-images.githubusercontent.com/58497792/179428492-ea30f6af-9942-4570-84e5-a559b58a92c1.png)
![image](https://user-images.githubusercontent.com/58497792/179428499-d54c18db-6622-47f0-bab7-5ecb98f95c69.png)

**Comment by g-fb** [comment]
Should be fixed now: https://github.com/g-fb/mangareader/releases/download/2.0.4/mangareader-2.0.4-windows-mingw_64-gcc.exe

**Comment by excalibur1010** [comment]
![image](https://user-images.githubusercontent.com/58497792/180740864-baa6a752-fedd-443f-83ad-bcf0fb273255.png)

thanks dev
