### ISSUE TITLE
Option in the page context menu to copy image

### ISSUE THREAD

**Issue by the-blank-x** [g-fb/mangareader#13]

**Comment by the-blank-x** [comment]
I want to use KSystemClipboard for this (mainly because [Flameshot uses it under Wayland](https://github.com/flameshot-org/flameshot/blob/3d21e4967b68e9ce80fb2238857aa1bf12c7b905/src/utils/screenshotsaver.cpp#L124) and [the reason for why it exists is because it works when the window is unfocused](https://api.kde.org/frameworks/kguiaddons/html/classKSystemClipboard.html#details) (matters at least to Wayland, don't know about X11 or Windows)), but this would need to bring in KGuiAddons (though that's probably not a point of contention, since it would be kinda weird to not have that while having other KDE framework stuff)

**Comment by g-fb** [comment]
> the reason for why it exists is because it works when the window is unfocused

When would the window not be focused, to require that feature?

**Comment by g-fb** [comment]
If you can't do that, then go ahead and use KSystemClipboard.
