### ISSUE TITLE
App Won't Remember Layout 

### ISSUE THREAD

**Issue by WinnerWind** [g-fb/mangareader#22]
When changing the panel layout of the manga folders and bookmarks, then closing the app, the app seems to forget its previous layout and reset to the default one, which is inconvenient for smaller displays, as shown in the video below.
System Information
![image](https://github.com/g-fb/mangareader/assets/71366717/3ba60cc0-6df9-42ec-9562-286cf63370d0)
Installed via GNOME Software

https://github.com/g-fb/mangareader/assets/71366717/05af3dc2-8305-4d66-9204-9718b7340469

**Comment by g-fb** [comment]
Should be fixed. You might have to delete the state file `~/.local/share/mangareader/mangareaderstaterc` or `~/.var/app/com.georgefb.mangareader/data/mangareader/mangareaderstaterc` for flatpak.

**Comment by WinnerWind** [comment]
Hi there!
GNOME Software's version of Manga Reader has not recieved an update yet, and hence removing the state file has not worked
I'll wait for an update for GNOME Software's version of Manga Reader then I'll let you know whether it works.

**Comment by WinnerWind** [comment]
Hi there! GNOME Software's version of Manga Reader received version 2.2.1 and now the layout is remembered. Thank you for fixing it!
