### ISSUE TITLE
support double-page splitting?

### ISSUE THREAD

**Issue by Smile8848** [g-fb/mangareader#3]
This is more convenient to read Japanese comic
like
![image](https://user-images.githubusercontent.com/31927778/215313593-578c66ad-9fcb-47cc-89a6-53e58f79c184.png)

**Comment by g-fb** [comment]
If by "double-page splitting" you mean turning a single image containing 2 manga pages into 2 images for each page, that won't happen. If you mean something else be more descriptive.
