### ISSUE TITLE
No option for making full screen default. Also, any way to make bookmarks?

### ISSUE THREAD

**Issue by linlinxza** [g-fb/mangareader#4]
It literally solved all my issues. I was trying to use Okular as it works with CBZ files. But since I used a touch screen, I could not get out of full screen. But this app does the trick and is much like Okular for the reading aspect of things.

I have a question, is there a way to make a bookmark of the page you were on? Also, is there a way to make it default to full screen (not a huge deal given the dilemma I was having when tying to use default viewer of Calibre where it was slow working with CBZ files and then dealing with Okular having no option to exit full screen via touch).

Anyway, thanks for making such a nifty app. ;)

PS: I would have sent this in an email, but I got error saying that your email can't be found.

**Comment by g-fb** [comment]
> is there a way to make a bookmark of the page you were on?

Right click an image.

> is there a way to make it default to full screen

No.

**Comment by g-fb** [comment]
Also https://github.com/g-fb/mangareader#status
