### ISSUE TITLE
Program closes after starting it

### ISSUE THREAD

**Issue by Gooboonsus** [g-fb/mangareader#7]
I have not yet used the Manga Reader yet, I just downloaded it with flatpack.

I was trying to get a directory to my local partition with stored manga, but I saw the message from Manjaro, something along the lines of "This program runs in the background". Then it asked "quitting this program may result in a loss of data" or something like that, then there were 2 buttons, typical "agree" or "close", again, I dont remember. I just hit the cross button to get rid of the message. Last thing I saw immediately after that is title cover for Attack on Titan, then Manga Reader closed.

Every time I try to open it will stay for 7 seconds then close again. Functionally it allows me to click buttons and interact with it, it works, but closes itself after a short time.

**Comment by g-fb** [comment]
No idea what is happening. On my machine I got no such issue.
Read https://community.kde.org/Guidelines_and_HOWTOs/Debugging/How_to_create_useful_crash_reports and try to get a backtrace.
You could also try with a new user account, to rule out any missconfiguration problems.

**Comment by Gooboonsus** [comment]
Okay, thank you for the update!

вт, 5 сент. 2023 г., 11:06 g-fb ***@***.***>:
